name: Deploy Horizon Banking

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Copy SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
          
            set -e
          
            echo "Starting script"
          
            # Pull latest code
            if [ -d ~/horizon-banking ]; then
              echo "Directory exists. Pulling latest code..."
              cd ~/horizon-banking && git pull
            else
              echo "Directory does not exist. Cloning repository..."
              git clone https://github.com/your-github-username/horizon-banking.git ~/horizon-banking
              cd ~/horizon-banking
            fi
          
            # Build Docker image
            echo "Building Docker image..."
            sudo docker build -t horizon-banking:latest .
          
            # Stop and remove existing container
            echo "Stopping existing container if it exists..."
            sudo docker stop horizon-banking || true
            echo "Removing existing container if it exists..."
            sudo docker rm horizon-banking || true
          
            # Run the container with environment variables
            echo "Running the Docker container..."
            sudo docker run -d \
              --name horizon-banking \
              --env-file /var/envs/horizon-banking.env \
              -p 3001:3000 \
              --restart unless-stopped \
              horizon-banking:latest
          
            # Clean up dangling images
            echo "Cleaning up dangling Docker images..."
            sudo docker image prune -f
          
            echo "Deployment script completed successfully."
          
          EOF